// Premmisus Nerve Center — Daily Summary Cron
// Runs at 6pm ET (Mon-Fri), sends formatted Telegram summary of today's activity
// Must be GET to be callable by Vercel cron (fixed 2026-04-21 after silent 405 failures)

import { NextResponse } from 'next/server';

const SUPABASE_URL = 'https://qokvhrrjrivvshaapncd.supabase.co';

export async function GET(request: Request) {
  // Required cron auth check
  const cronSecret = process.env.CRON_SECRET;
  const auth = request.headers.get('authorization');
  if (!cronSecret || auth !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const SB_KEY = process.env.SUPABASE_SERVICE_KEY || '';
  const BOT_TOKEN = (process.env.TELEGRAM_BOT_TOKEN || '').trim();
  const CHAT_ID = (process.env.TELEGRAM_CHAT_ID || '').trim();

  if (!SB_KEY || !BOT_TOKEN || !CHAT_ID) return NextResponse.json({ error: 'Not configured' }, { status: 500 });

  try {
    const today = new Date().toISOString().split('T')[0];

    // Get all reps
    const repsRes = await fetch(`${SUPABASE_URL}/rest/v1/reps?select=id,name,role&order=created_at.asc`, {
      headers: { 'apikey': SB_KEY, 'Authorization': `Bearer ${SB_KEY}` },
    });
    const reps = await repsRes.json();

    // Get today's call logs
    const logsRes = await fetch(`${SUPABASE_URL}/rest/v1/call_logs?select=*&created_at=gte.${today}T00:00:00&order=created_at.desc`, {
      headers: { 'apikey': SB_KEY, 'Authorization': `Bearer ${SB_KEY}` },
    });
    const logs = await logsRes.json();

    if (!Array.isArray(logs)) return NextResponse.json({ message: 'No logs' });

    // Build summary per rep
    let summary = `📊 *DAILY SUMMARY — ${today}*\n`;
    let totalCalls = 0;
    let totalBookings = 0;

    for (const rep of reps.filter((r: any) => r.role !== 'director')) {
      const repLogs = logs.filter((l: any) => l.rep_id === rep.id);
      if (repLogs.length === 0) {
        summary += `\n*${rep.name}:*\n  ⚠️ No calls today\n`;
        continue;
      }

      const calls = repLogs.length;
      const connects = repLogs.filter((l: any) => !['no_answer', 'wrong_number'].includes(l.outcome)).length;
      const bookings = repLogs.filter((l: any) => ['booked_call', 'discovery_completed'].includes(l.outcome)).length;
      const callbacks = repLogs.filter((l: any) => l.outcome === 'callback_requested').length;
      const notInterested = repLogs.filter((l: any) => l.outcome === 'not_interested').length;
      const wrongNumbers = repLogs.filter((l: any) => l.outcome === 'wrong_number').length;
      const connectRate = calls > 0 ? Math.round((connects / calls) * 100) : 0;

      // Find longest call
      const withDuration = repLogs.filter((l: any) => l.duration_seconds && l.duration_seconds > 0);
      const longest = withDuration.sort((a: any, b: any) => b.duration_seconds - a.duration_seconds)[0];
      const longestStr = longest
        ? `${Math.floor(longest.duration_seconds / 60)}m ${longest.duration_seconds % 60}s with ${longest.business_name || 'Unknown'}`
        : 'N/A';

      totalCalls += calls;
      totalBookings += bookings;

      summary += `\n*${rep.name}:*\n`;
      summary += `  📞 ${calls} calls | ${connects} connects | ${connectRate}% rate\n`;
      summary += `  🟢 ${bookings} booking${bookings !== 1 ? 's' : ''} | 🟡 ${callbacks} callback${callbacks !== 1 ? 's' : ''}\n`;
      if (wrongNumbers > 0) summary += `  ⚠️ ${wrongNumbers} wrong numbers\n`;
      if (notInterested > 0) summary += `  🔴 ${notInterested} not interested\n`;
      summary += `  🏆 Best call: ${longestStr}\n`;

      // Coaching tips
      if (notInterested >= 3) summary += `  💡 _Review objection handling scripts_\n`;
      if (wrongNumbers >= 5) summary += `  💡 _Lead data quality issue — consider scrubbing list_\n`;
      if (connectRate < 20) summary += `  💡 _Low connect rate — try different calling times_\n`;
    }

    summary += `\n*TOTALS:* ${totalCalls} calls | ${totalBookings} bookings`;
    summary += `\n\n_Generated by Premmisus Nerve Center_`;

    // Send to Telegram
    const teleRes = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chat_id: CHAT_ID, text: summary, parse_mode: 'Markdown' }),
    });

    const teleData = await teleRes.json();

    // Log it
    await fetch(`${SUPABASE_URL}/rest/v1/notifications_log`, {
      method: 'POST',
      headers: { 'apikey': SB_KEY, 'Authorization': `Bearer ${SB_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'daily_summary', recipient: 'director', channel: 'telegram', message: `${totalCalls} calls, ${totalBookings} bookings` }),
    });

    return NextResponse.json({ success: teleData.ok, totalCalls, totalBookings });

  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
